version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8888:8888
    extra_hosts:
      - "host.docker.internal:host-gateway"
